
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace global

[<assembly: System.Reflection.AssemblyMetadataAttribute("Root", "Plugins/resharper-fsharp/ReSharper.FSharp/test/src/FSharp.Common.Tests")>]
do ()