
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace global

[<assembly: System.Reflection.AssemblyMetadataAttribute("Root", "Plugins/resharper-fsharp/ReSharper.FSharp/test/src/FSharp.Intentions.Tests")>]
do ()
#if INDEPENDENT_BUILD
namespace NUnit.Framework

type TestAttribute = NUnit.Framework.TestAttribute
type TestCaseAttribute = NUnit.Framework.TestCaseAttribute
type TestCaseSourceAttribute = NUnit.Framework.TestCaseSourceAttribute
type TestFixtureAttribute = NUnit.Framework.TestFixtureAttribute
type TestFixtureSourceAttribute = NUnit.Framework.TestFixtureSourceAttribute
type SetUpFixtureAttribute = NUnit.Framework.SetUpFixtureAttribute
type ExplicitAttribute = NUnit.Framework.ExplicitAttribute
type CategoryAttribute = NUnit.Framework.CategoryAttribute
type IgnoreAttribute = NUnit.Framework.IgnoreAttribute
do()
#else
namespace NUnit.Framework

type TestAttribute = JetBrains.TestFramework.TestAttribute
type TestCaseAttribute = JetBrains.TestFramework.TestCaseAttribute
type TestCaseSourceAttribute = JetBrains.TestFramework.TestCaseSourceAttribute
type TestFixtureAttribute = JetBrains.TestFramework.TestFixtureAttribute
type TestFixtureSourceAttribute = JetBrains.TestFramework.TestFixtureSourceAttribute
type SetUpFixtureAttribute = JetBrains.TestFramework.SetUpFixtureAttribute
type ExplicitAttribute = JetBrains.TestFramework.ExplicitAttribute
type CategoryAttribute = JetBrains.TestFramework.CategoryAttribute
type IgnoreAttribute = JetBrains.TestFramework.IgnoreAttribute
do()
#endif