// <auto-generated/>
namespace JetBrains.ReSharper.Plugins.FSharp.Psi.Daemon.Resources

open System
open JetBrains.Application.I18n
open JetBrains.DataFlow
open JetBrains.Diagnostics
open JetBrains.Lifetimes
open JetBrains.Util
open JetBrains.Util.Logging
open JetBrains.Application.I18n.Plurals

[<global.System.Diagnostics.DebuggerNonUserCode>]
[<global.System.Runtime.CompilerServices.CompilerGenerated>]
type public Strings() =
    static let logger = Logger.GetLogger("JetBrains.ReSharper.Plugins.FSharp.Psi.Daemon.Resources.Strings")

    static let mutable resourceManager = null

    static do
        CultureContextComponent.Instance.Change.Advise(Lifetime.Eternal, fun (args:PropertyChangedEventArgs<CultureContextComponent>) ->
            let instance = if args.HasNew then args.New else null
            if instance <> null then
                resourceManager <- Lazy<JetResourceManager>(fun _ ->
                    instance.CreateResourceManager("JetBrains.ReSharper.Plugins.FSharp.Psi.Daemon.Resources.Strings",
                                typeof<Strings>.Assembly))
            else
                resourceManager <- null)

    [<global.System.ComponentModel.EditorBrowsable(global.System.ComponentModel.EditorBrowsableState.Advanced)>]
    static member ResourceManager: JetResourceManager =
        match resourceManager with
            | null -> ErrorJetResourceManager.Instance
            | _ -> resourceManager.Value

    static member Choice(format: string, [<ParamArray>] args: Object array): string =
        match Strings.ResourceManager.ChoiceFormatter with
            | null -> "???"
            | formatter -> String.Format(formatter, format, args)

    static member FSharpInferredTypeHighlighting_ProviderId = Strings.ResourceManager.GetString("FSharpInferredTypeHighlighting_ProviderId")
    static member FSharpInferredTypeHighlighting_TooltipText = Strings.ResourceManager.GetString("FSharpInferredTypeHighlighting_TooltipText")
    static member InferredTypeCodeVisionProvider_TypeCopied_TooltipText = Strings.ResourceManager.GetString("InferredTypeCodeVisionProvider_TypeCopied_TooltipText")
    static member FSharpSignatureHints_SettingsDescription = Strings.ResourceManager.GetString("FSharpSignatureHints_SettingsDescription")
    static member FSharpSignatureHints_TopLevelMembersSettings_Header = Strings.ResourceManager.GetString("FSharpSignatureHints_TopLevelMembersSettings_Header")
    static member FSharpOptionPageTitle = Strings.ResourceManager.GetString("FSharpOptionPageTitle")
    static member FSharpTypeHints_OptionsPage_Title = Strings.ResourceManager.GetString("FSharpTypeHints_OptionsPage_Title")
    static member FSharpSignatureHints_LocalBindingsSettings_Header = Strings.ResourceManager.GetString("FSharpSignatureHints_LocalBindingsSettings_Header")
    static member FSharpSignatureHints_TopLevelMembersSettings_Comment = Strings.ResourceManager.GetString("FSharpSignatureHints_TopLevelMembersSettings_Comment")