// <auto-generated/>
namespace NUnit.Framework

type TestAttribute = JetBrains.TestFramework.TestAttribute
type TestCaseAttribute = JetBrains.TestFramework.TestCaseAttribute
type TestCaseSourceAttribute = JetBrains.TestFramework.TestCaseSourceAttribute
type TestFixtureAttribute = JetBrains.TestFramework.TestFixtureAttribute
type TestFixtureSourceAttribute = JetBrains.TestFramework.TestFixtureSourceAttribute
type SetUpFixtureAttribute = JetBrains.TestFramework.SetUpFixtureAttribute
type ExplicitAttribute = JetBrains.TestFramework.ExplicitAttribute
type CategoryAttribute = JetBrains.TestFramework.CategoryAttribute
type IgnoreAttribute = JetBrains.TestFramework.IgnoreAttribute