package com.jetbrains.rider.plugins.fsharp.spellchecker

import com.jetbrains.rider.ideaInterop.fileTypes.fsharp.FSharpLanguage
import com.jetbrains.rider.spellChecker.BackendLanguageSpellcheckingStrategy

class FSharpSpellcheckingStrategy : BackendLanguageSpellcheckingStrategy(FSharpLanguage)