name: "build-test"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  test-backend:
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        image: [windows-latest]
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.github/nuget-packages
      GRADLE_USER_HOME: ${{ github.workspace }}/.github/gradle
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - uses: actions/checkout@v4

      - name: Gradle Wrapper Cache
        uses: actions/cache@v4
        with:
          path: ${{ env.GRADLE_USER_HOME }}/wrapper
          key: ${{ runner.os }}.gradle-wrapper.${{ hashFiles('rider-fsharp/gradle/**') }}

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.3

      - name: NuGet Cache
        uses: actions/cache@v4
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}.nuget.${{ hashFiles('ReSharper.FSharp/**/*proj') }}+${{ hashFiles('ReSharper.FSharp/**/*.targets') }}

      - name: Gradlew Prepare
        working-directory: ./rider-fsharp
        run: ./gradlew prepare

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          global-json-file: ReSharper.FSharp/global.json

      - name: Add MSBuild to PATH # for tests
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build ReSharper.FSharp
        working-directory: ./ReSharper.FSharp
        run: dotnet build -p:RunningOnGitHubActions=true

      - name: Build Plugin Frontend
        working-directory: ./rider-fsharp
        if: ${{ success() }} || ${{ failure() }}
        run: ./gradlew buildPlugin

      - name: Test Plugin Frontend
        working-directory: ./rider-fsharp
        if: ${{ success() }} || ${{ failure() }}
        run: ./gradlew test

      - name: Stop Gradle Daemon # to collect Gradle cache
        working-directory: ./rider-fsharp
        run: ./gradlew --stop
